name: authentication_repository
description: Dart package which manages the authentication domain.
version: 1.0.0
publish_to: none

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  cache:
    path: ../cache
  cloud_firestore: ^3.1.13
  equatable: ^2.0.3
  firebase_auth: ^3.3.12
  firebase_core: ^1.5.0
  flutter:
    sdk: flutter
  google_sign_in: ^5.0.7
  json_annotation: 4.4.0
  json_serializable: any
  meta: ^1.3.0
  very_good_analysis: ^2.4.0

dev_dependencies:
  build_runner: ^2.1.9
  flutter_test:
    sdk: flutter
  mocktail: ^0.2.0

