// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWv_dM95G9px5wdMpKkk6bpCLCmK6X1-s',
    appId: '1:838181007011:web:5454ed994c6fb69ea19916',
    messagingSenderId: '838181007011',
    projectId: 'upcarta-77024',
    authDomain: 'upcarta-77024.firebaseapp.com',
    databaseURL: 'https://upcarta-77024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'upcarta-77024.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBa30_-u1oSi0ORrXfsVnjdJF2mot3Sozk',
    appId: '1:838181007011:android:7f9c3cfc8353a0dfa19916',
    messagingSenderId: '838181007011',
    projectId: 'upcarta-77024',
    databaseURL: 'https://upcarta-77024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'upcarta-77024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCNogvjbrwOpdgdtEOV2w52pOtVDfQHF4k',
    appId: '1:838181007011:ios:a3d324b0e2e7c8c2a19916',
    messagingSenderId: '838181007011',
    projectId: 'upcarta-77024',
    databaseURL: 'https://upcarta-77024-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'upcarta-77024.appspot.com',
    iosClientId: '838181007011-570ica2df8p06873csimkj1ha42fc9dr.apps.googleusercontent.com',
    iosBundleId: 'com.upcarta.app',
  );
}
