import 'package:upcarta_mobile_app/models/models.dart';

final List<Content> contents = <Content>[
  Content(
    title: "TOP SCREEN",
    username: "dora",
    postId: "1",
    contentType: ContentType.book,
    uId: '',
    url: 'www.google.com',
    description: 'berna',
    imageLocation:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now().toString(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  Content(
    title: "SECOND POST",
    postId: "2",
    username: "dora",
    contentType: ContentType.book,
    uId: '',
    url: 'www.google.com',
    description: 'berna',
    imageLocation:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now().toString(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  Content(
    title: "THIRD POST",
    username: "berna",
    postId: "3",
    contentType: ContentType.book,
    uId: '',
    url: 'www.google.com',
    description: 'berna',
    imageLocation:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now().toString(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  Content(
    title: "FOURTH POST",
    postId: "4",
    username: "berna",
    contentType: ContentType.book,
    uId: '',
    url: 'www.google.com',
    description: 'berna',
    imageLocation:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now().toString(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  Content(
    title: "FIFTH POST",
    username: "berna",
    postId: "2",
    contentType: ContentType.book,
    uId: '',
    url: 'www.google.com',
    description: 'berna',
    imageLocation:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now().toString(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  /*
  Content(
    title: "SIXTH POST",
    id: "2",
    contentType: ContentType.book,
    posterID: '',
    link: 'www.google.com',
    description: 'berna',
    creatorID: '',
    image:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  Content(
    title: "SEVENTH POST",
    id: "2",
    contentType: ContentType.book,
    posterID: '',
    link: 'www.google.com',
    description: 'berna',
    creatorID: '',
    image:
        'https://i.pinimg.com/originals/e8/15/b9/e815b94b7a82d7c6e2f4c791bf984d98.jpg',
    contentTopic: '',
    createDate: DateTime.now(),
    recommendationText: '',
    recommendersIDs: [],
  ),
  */
];
